# -*- coding: utf-8 -*-
"""Assignment1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HVM8baaxSKzIAnYraiJ6uAiPqEWetDph
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('House_Price_India.csv')

#univariate

sns.histplot(data = df, x="living area")
plt.show()

sns.boxplot(data=df, y="living area")
plt.show()

sns.countplot(data=df, x="living area")
plt.show()

sns.displot(data=df, x="living area")
plt.show()

#Bivariate

sns.scatterplot(data=df, x="living area", y="Area of the house(excluding basement)")
plt.show()

sns.lineplot(data=df, x="living area", y="Area of the house(excluding basement)")
plt.show()

sns.heatmap(data=df.corr(), annot=True)
plt.show()

#Multi-variate

sns.pairplot(data=df)
plt.show()

sns.heatmap(data=df.corr(), annot=True)
plt.show()

import pandas as pd

df = pd.read_csv('House_Price_India.csv')

print(df.head())

print(df.shape)

print(df.columns)

print(df.describe())

print("Mean:", df['Area of the house(excluding basement)'].mean())
print("Median:", df['Area of the house(excluding basement)'].median())
print("Mode:", df['Area of the house(excluding basement)'].mode())
print("Standard Deviation:", df['Area of the house(excluding basement)'].std())

print(df.corr())

print(df.cov())

print(df['Area of the house(excluding basement)'].value_counts())

import pandas as pd

df = pd.read_csv('House_Price_India.csv')

print(df.isna().sum())

# Remove rows with missing values
df.dropna(inplace=True)

# Remove columns with missing values
df.dropna(axis=1, inplace=True)

df.fillna(value=0, inplace=True)

# Fill missing values with the mean of the column
df['Area of the house(excluding basement)'].fillna(df['Area of the house(excluding basement)'].mean(), inplace=True)

# Fill missing values with the median of the column
df['Area of the house(excluding basement)'].fillna(df['Area of the house(excluding basement)'].median(), inplace=True)

# Fill missing values with the mode of the column
df['Area of the house(excluding basement)'].fillna(df['Area of the house(excluding basement)'].mode()[0], inplace=True)